/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReadRouteImport } from './routes/read'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromptsPromptIdRouteImport } from './routes/prompts.$promptId'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsPromptIdRoute = PromptsPromptIdRouteImport.update({
  id: '/$promptId',
  path: '/$promptId',
  getParentRoute: () => PromptsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRouteWithChildren
  '/read': typeof ReadRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRouteWithChildren
  '/read': typeof ReadRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRouteWithChildren
  '/read': typeof ReadRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/demo/api/names': typeof DemoApiNamesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prompts'
    | '/read'
    | '/sign-in'
    | '/api/chat'
    | '/prompts/$promptId'
    | '/demo/api/names'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prompts'
    | '/read'
    | '/sign-in'
    | '/api/chat'
    | '/prompts/$promptId'
    | '/demo/api/names'
  id:
    | '__root__'
    | '/'
    | '/prompts'
    | '/read'
    | '/sign-in'
    | '/api/chat'
    | '/prompts/$promptId'
    | '/demo/api/names'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptsRoute: typeof PromptsRouteWithChildren
  ReadRoute: typeof ReadRoute
  SignInRoute: typeof SignInRoute
  ApiChatRoute: typeof ApiChatRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$promptId': {
      id: '/prompts/$promptId'
      path: '/$promptId'
      fullPath: '/prompts/$promptId'
      preLoaderRoute: typeof PromptsPromptIdRouteImport
      parentRoute: typeof PromptsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PromptsRouteChildren {
  PromptsPromptIdRoute: typeof PromptsPromptIdRoute
}

const PromptsRouteChildren: PromptsRouteChildren = {
  PromptsPromptIdRoute: PromptsPromptIdRoute,
}

const PromptsRouteWithChildren =
  PromptsRoute._addFileChildren(PromptsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptsRoute: PromptsRouteWithChildren,
  ReadRoute: ReadRoute,
  SignInRoute: SignInRoute,
  ApiChatRoute: ApiChatRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
